version: 2
defaults: &defaults
  docker:
    - image: circleci/python:2.7-stretch-browsers

install_awscli: &install_awscli
  name: "Install awscli"
  command: |
    sudo pip install awscli awsebcli
    aws --version
    eb --version
  

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 'docker run --rm -ti -v $PWD:/app onesysadmin/grails:1.3 grails war scorecard.war'

  deploy_prod:
    <<: *defaults
    steps:
      - run: *install_awscli
      - run: .deploy/ebs_deploy.sh scorecard-tool PROD $CIRCLE_BUILD_NUM

  deploy_dev:
    <<: *defaults
    steps:
      - run: *install_awscli
      - run: .deploy/ebs_deploy.sh scorecard-tool DEV $CIRCLE_BUILD_NUM

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_dev:
          filters:
            branches:
              only: dev
          requires:
            - build
      - deploy_prod:
          filters:
            branches:
              only: master
          requires:
            - build