version: 2
defaults: &defaults
  docker:
    - image: circleci/buildpack-deps:18.04-scm-browsers
install_awscli: &install_awscli
  name: "Install awscli"
  command: |
    sudo apt-get update
    sudo apt-get install python-pip
    sudo pip install awscli awsebcli
    aws --version
    eb --version

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: *install_awscli
      - setup_remote_docker
      - run: docker run --rm -ti -v $PWD:/app onesysadmin/grails:1.3 grails war scorecard.war

  deploy_prod:
    <<: *defaults
    steps:
      - run: *install_awscli
      - setup_remote_docker
      - run: .deploy/ebs_deploy.sh scorecard-tool PROD $CIRCLE_BUILD_NUM

  deploy_dev:
    <<: *defaults
    steps:
      - run: *install_awscli
      - setup_remote_docker
      - run: .deploy/ebs_deploy.sh scorecard-tool DEV $CIRCLE_BUILD_NUM

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_dev:
          filters:
            branches:
              only: dev
          requires:
            - build
      - deploy_prod:
          filters:
            branches:
              only: master
          requires:
            - build